"""YouTube 内置登录：Playwright 持久化 profile 一次人工登录，此后自动导出 cookies。

官方 OAuth 对 yt-dlp 不可用（FR-21 背景），改为本机 Chromium 持久化 profile 方案：
POST /config/youtube/login 弹窗人工登录 → 登录态存 PROFILE_DIR →
export_cookies() 随时 headless 导出 Netscape cookies.txt 文本，供 yt-dlp 使用。

并发约束：同一 profile 目录同时只能被一个 Chromium 实例占用（ProcessSingleton），
进程内用 _login_task 单例 + _EXPORT_MUTEX 串行化；跨进程（api/worker 同时导出）
冲突时导出抛错，调用方回退存量 cookies_text（video_source.build_ytdlp_opts）。
"""

import asyncio
import shutil
import sqlite3
import tempfile
import threading
import time
from contextlib import suppress
from pathlib import Path

# 项目根 data/ 下（与场景 YAML、词典缓存同级），已加入根 .gitignore
PROFILE_DIR = Path(__file__).resolve().parents[2] / "data" / "yt-profile"

LOGIN_URL = "https://accounts.google.com/ServiceLogin?service=youtube"
YOUTUBE_URL = "https://www.youtube.com/"
LOGIN_TIMEOUT_S = 300  # 5 分钟没登录完自动关窗
_POLL_INTERVAL_S = 2.0
# 登录态特征 cookie：任一名称包含以下子串即视为已登录
LOGIN_COOKIE_MARKERS = ("SAPISID", "LOGIN_INFO")
# 降低 Google「此浏览器或应用可能不安全」拦截
_LAUNCH_ARGS = ["--disable-blink-features=AutomationControlled"]
_VIEWPORT = {"width": 1100, "height": 780}


class YoutubeLoginError(Exception):
    """未登录 / profile 被占用 / 导出失败。"""


# ---- 进程内状态（api 进程使用；worker 进程只调 export_cookies_sync） ----

_login_task: asyncio.Task | None = None  # 单例锁：防重复开窗
_login_result: str | None = None  # success | timeout | closed | error:<msg>
_pending_sync = False  # 登录成功后待「导出 + 写凭据」标记，由路由消费
_EXPORT_MUTEX = threading.Lock()  # 导出串行化（进程内）


def login_window_open() -> bool:
    return _login_task is not None and not _login_task.done()


def last_login_result() -> str | None:
    return _login_result


def pending_sync() -> bool:
    """登录刚成功、cookies 尚未导出写入凭据库。"""
    return _pending_sync and not login_window_open()


def mark_synced() -> None:
    global _pending_sync
    _pending_sync = False


def start_login_window() -> bool:
    """后台任务开登录窗；已有窗口开着返回 False。需在事件循环内调用。"""
    global _login_task
    if login_window_open():
        return False
    _login_task = asyncio.get_running_loop().create_task(launch_login_window())
    return True


# ---- 登录窗口 ----


async def _context_logged_in(context) -> bool:
    cookies = await context.cookies(YOUTUBE_URL)
    return any(
        marker in c.get("name", "") for c in cookies for marker in LOGIN_COOKIE_MARKERS
    )


async def launch_login_window() -> None:
    """弹出有头 Chromium 让用户人工登录；轮询到登录态后跳转 YouTube 确认并关窗。

    结果落 _login_result；成功置 _pending_sync，由 /config/youtube/login/status
    路由消费（导出 cookies 写凭据）。用户中途关窗按 closed 处理（profile 可能已含
    登录态，profile_logged_in 兜底判定）。
    """
    global _login_result, _pending_sync
    from playwright.async_api import async_playwright

    _login_result = None
    success = False
    try:
        PROFILE_DIR.mkdir(parents=True, exist_ok=True)
        async with async_playwright() as p:
            context = await p.chromium.launch_persistent_context(
                str(PROFILE_DIR),
                headless=False,
                viewport=_VIEWPORT,
                args=_LAUNCH_ARGS,
            )
            try:
                page = context.pages[0] if context.pages else await context.new_page()
                await page.goto(LOGIN_URL, wait_until="domcontentloaded")
                deadline = time.monotonic() + LOGIN_TIMEOUT_S
                while time.monotonic() < deadline:
                    try:
                        if await _context_logged_in(context):
                            success = True
                            # 跳转 youtube.com 确认登录态可访问后再关窗
                            with suppress(Exception):
                                await page.goto(YOUTUBE_URL, wait_until="domcontentloaded")
                                await asyncio.sleep(1.5)
                            break
                    except Exception:  # 用户手动关窗：context 已失效
                        _login_result = "closed"
                        break
                    await asyncio.sleep(_POLL_INTERVAL_S)
                else:
                    _login_result = "timeout"
            finally:
                with suppress(Exception):
                    await context.close()
    except Exception as exc:
        _login_result = f"error:{type(exc).__name__}: {exc}"
        return
    # 窗口关闭后 cookie 已落盘：手动关窗/超时但其实已登录的情况兜底
    if not success and _login_result in ("closed", "timeout"):
        success = profile_logged_in()
    if success:
        _login_result = "success"
        _pending_sync = True


# ---- cookies 导出 ----


def cookies_to_netscape(cookies: list[dict]) -> str:
    """Playwright cookie dict 列表 → Netscape cookies.txt 文本（yt-dlp cookiefile 格式）。

    HttpOnly cookie 行加 #HttpOnly_ 前缀；会话 cookie（expires=-1）过期时间记 0。
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by lingua-next. Do not edit.",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", "")
        include_sub = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure") else "FALSE"
        expires = c.get("expires")
        expiry = 0 if expires is None or expires < 0 else int(expires)
        prefix = "#HttpOnly_" if c.get("httpOnly") else ""
        lines.append(
            f"{prefix}{domain}\t{include_sub}\t{c.get('path', '/')}\t{secure}\t"
            f"{expiry}\t{c.get('name', '')}\t{c.get('value', '')}"
        )
    return "\n".join(lines) + "\n"


def _domain_relevant(domain: str) -> bool:
    d = domain.lstrip(".")
    return d == "youtube.com" or d.endswith(".youtube.com") or d == "google.com" \
        or d.endswith(".google.com")


async def export_cookies() -> str:
    """headless 打开持久化 profile，导出 youtube/google 域 cookies 为 Netscape 文本。

    未登录（无 SAPISID/LOGIN_INFO）抛 YoutubeLoginError。不做并发防护，
    调用方统一走 export_cookies_sync（带互斥锁）。
    """
    if login_window_open():
        raise YoutubeLoginError("登录窗口未关闭，等登录完成后再导出")
    if not PROFILE_DIR.exists():
        raise YoutubeLoginError("尚未登录：profile 不存在，先在设置里完成 YouTube 登录")
    from playwright.async_api import async_playwright

    try:
        async with async_playwright() as p:
            context = await p.chromium.launch_persistent_context(
                str(PROFILE_DIR), headless=True, args=_LAUNCH_ARGS
            )
            try:
                cookies = await context.cookies()
            finally:
                await context.close()
    except YoutubeLoginError:
        raise
    except Exception as exc:  # profile 被占用 / Chromium 启动失败
        raise YoutubeLoginError(f"cookies 导出失败：{type(exc).__name__}: {exc}") from exc

    picked = [c for c in cookies if _domain_relevant(c.get("domain", ""))]
    logged_in = any(
        marker in c.get("name", "") for c in picked for marker in LOGIN_COOKIE_MARKERS
    )
    if not logged_in:
        raise YoutubeLoginError("profile 未登录（无 SAPISID cookie），先在设置里完成 YouTube 登录")
    return cookies_to_netscape(picked)


def export_cookies_sync() -> str:
    """同步导出入口：仅限无事件循环的线程调用（worker 线程池 / asyncio.to_thread）。"""
    with _EXPORT_MUTEX:
        return asyncio.run(export_cookies())


# ---- 快速登录判定（不起浏览器） ----


def profile_logged_in() -> bool:
    """读 profile 的 Chromium Cookies SQLite 判断登录态（cookie 值加密但名字明文）。

    拷贝到临时文件再读：浏览器占用原文件时 sqlite 会锁。读不出来一律按未登录。
    """
    db = PROFILE_DIR / "Default" / "Cookies"
    if not db.exists():
        return False
    tmp = Path(tempfile.mkstemp(prefix="yt-cookies-db-", suffix=".sqlite")[1])
    try:
        shutil.copyfile(db, tmp)
        conn = sqlite3.connect(tmp)
        try:
            rows = conn.execute(
                "SELECT count(*) FROM cookies WHERE host_key LIKE '%youtube.com' "
                "AND (name LIKE '%SAPISID%' OR name LIKE '%LOGIN_INFO%')"
            ).fetchone()
            return bool(rows and rows[0])
        finally:
            conn.close()
    except Exception:
        return False
    finally:
        tmp.unlink(missing_ok=True)
