"""srs columns and review log

Revision ID: 0538bbc594b2
Revises: bf42657f21cb
Create Date: 2026-08-17 09:40:28.560378
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0538bbc594b2'
down_revision: str | None = 'bf42657f21cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('state_before', sa.String(length=16), nullable=False),
    sa.Column('review_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('elapsed_days', sa.Float(), nullable=True),
    sa.Column('fsrs_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # 已有行回填 reading（阅读收藏来源）
    op.add_column('vocab_entry', sa.Column('source', sa.String(length=16), nullable=False, server_default='reading'))
    op.add_column('vocab_entry', sa.Column('fsrs_card', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('vocab_entry', sa.Column('due_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vocab_entry', sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_vocab_entry_due_at'), 'vocab_entry', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vocab_entry_due_at'), table_name='vocab_entry')
    op.drop_column('vocab_entry', 'last_review_at')
    op.drop_column('vocab_entry', 'due_at')
    op.drop_column('vocab_entry', 'fsrs_card')
    op.drop_column('vocab_entry', 'source')
    op.drop_table('review_log')
    # ### end Alembic commands ###
