"""素材分组与AI标签

Revision ID: 104fae187fab
Revises: d10109fd4f43
Create Date: 2026-08-20 10:11:48.046205
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '104fae187fab'
down_revision: str | None = 'd10109fd4f43'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('studio_asset_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['studio_asset_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image_asset', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('image_asset', sa.Column('caption', sa.Text(), nullable=True))
    op.add_column('image_asset', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('image_asset', sa.Column('tagged_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_image_asset_group_id'), 'image_asset', ['group_id'], unique=False)
    # 外键显式命名：自动生成的 None 在 downgrade 的 drop_constraint 里没法回填
    op.create_foreign_key('fk_image_asset_group', 'image_asset', 'studio_asset_group', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_image_asset_group', 'image_asset', type_='foreignkey')
    op.drop_index(op.f('ix_image_asset_group_id'), table_name='image_asset')
    op.drop_column('image_asset', 'tagged_at')
    op.drop_column('image_asset', 'tags')
    op.drop_column('image_asset', 'caption')
    op.drop_column('image_asset', 'group_id')
    op.drop_table('studio_asset_group')
    # ### end Alembic commands ###
