"""跟读录音落库

Revision ID: 1439366fc2ed
Revises: b5af0e296236
Create Date: 2026-08-19 04:59:52.273886
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1439366fc2ed'
down_revision: str | None = 'b5af0e296236'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shadow_recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.Column('audio_key', sa.String(length=255), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('accuracy', sa.Integer(), nullable=True),
    sa.Column('diff', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['subtitle_sentence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unit_id'], ['study_unit.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shadow_recording_sentence', 'shadow_recording', ['sentence_id', 'created_at'], unique=False)
    op.create_index('ix_shadow_recording_video', 'shadow_recording', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shadow_recording_video', table_name='shadow_recording')
    op.drop_index('ix_shadow_recording_sentence', table_name='shadow_recording')
    op.drop_table('shadow_recording')
    # ### end Alembic commands ###
