"""音标与语法模块建表

Revision ID: 1cc5a88fe610
Revises: 427a2a59622a
Create Date: 2026-08-19 14:02:26.639629
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1cc5a88fe610'
down_revision: str | None = '427a2a59622a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_point',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ext_id', sa.String(length=16), nullable=False),
    sa.Column('shorthand_code', sa.String(length=64), nullable=False),
    sa.Column('item', sa.String(length=256), nullable=False),
    sa.Column('item_ja', sa.String(length=256), nullable=True),
    sa.Column('item_zh', sa.String(length=256), nullable=True),
    sa.Column('sentence_type', sa.String(length=32), nullable=True),
    sa.Column('cefr_level', sa.String(length=8), nullable=True),
    sa.Column('cefrj_level', sa.String(length=8), nullable=True),
    sa.Column('note_zh', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('pattern_regex', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ext_id')
    )
    op.create_index('ix_grammar_point_cat_order', 'grammar_point', ['category', 'order_index'], unique=False)
    op.create_index(op.f('ix_grammar_point_category'), 'grammar_point', ['category'], unique=False)
    op.create_index(op.f('ix_grammar_point_cefr_level'), 'grammar_point', ['cefr_level'], unique=False)
    op.create_index(op.f('ix_grammar_point_shorthand_code'), 'grammar_point', ['shorthand_code'], unique=False)
    op.create_table('minimal_pair',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrast_group', sa.String(length=32), nullable=False),
    sa.Column('word_a', sa.String(length=64), nullable=False),
    sa.Column('word_b', sa.String(length=64), nullable=False),
    sa.Column('ipa_a', sa.String(length=128), nullable=False),
    sa.Column('ipa_b', sa.String(length=128), nullable=False),
    sa.Column('phone_a', sa.String(length=8), nullable=False),
    sa.Column('phone_b', sa.String(length=8), nullable=False),
    sa.Column('diff_index', sa.Integer(), nullable=False),
    sa.Column('freq_rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word_a', 'word_b', 'diff_index', name='uq_minimal_pair')
    )
    op.create_index(op.f('ix_minimal_pair_contrast_group'), 'minimal_pair', ['contrast_group'], unique=False)
    op.create_index('ix_minimal_pair_group_freq', 'minimal_pair', ['contrast_group', 'freq_rank'], unique=False)
    op.create_table('phoneme',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('symbol_us', sa.String(length=16), nullable=True),
    sa.Column('arpabet', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('manner', sa.String(length=32), nullable=False),
    sa.Column('place', sa.String(length=32), nullable=False),
    sa.Column('voiced', sa.Boolean(), nullable=False),
    sa.Column('zh_name', sa.String(length=64), nullable=False),
    sa.Column('examples', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('common_errors', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('svg_frames', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('chart_x', sa.Float(), nullable=True),
    sa.Column('chart_y', sa.Float(), nullable=True),
    sa.Column('chart_to_x', sa.Float(), nullable=True),
    sa.Column('chart_to_y', sa.Float(), nullable=True),
    sa.Column('highlight', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('contrast_with', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('phoneme_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('card_key', sa.String(length=64), nullable=False),
    sa.Column('question_id', sa.String(length=128), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phoneme_attempt_card_key'), 'phoneme_attempt', ['card_key'], unique=False)
    op.create_index(op.f('ix_phoneme_attempt_created_at'), 'phoneme_attempt', ['created_at'], unique=False)
    op.create_table('phoneme_card_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('card_key', sa.String(length=64), nullable=False),
    sa.Column('fsrs_card', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('trained_seconds', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'card_key', name='uq_phoneme_card')
    )
    op.create_index(op.f('ix_phoneme_card_state_due_at'), 'phoneme_card_state', ['due_at'], unique=False)
    op.create_table('phoneme_difficulty',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('low_score_rate', sa.Float(), nullable=False),
    sa.Column('mean_score', sa.Float(), nullable=False),
    sa.Column('sample_n', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('word_phoneme',
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('ipa_us', sa.String(length=256), nullable=True),
    sa.Column('ipa_uk', sa.String(length=256), nullable=True),
    sa.Column('arpabet', sa.String(length=256), nullable=True),
    sa.Column('syllables', sa.Integer(), nullable=True),
    sa.Column('stress', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_index('ix_word_phoneme_source', 'word_phoneme', ['source'], unique=False)
    op.create_table('grammar_card',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('widget', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('schedulable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grammar_card_grammar_point_id'), 'grammar_card', ['grammar_point_id'], unique=False)
    op.create_index(op.f('ix_grammar_card_kind'), 'grammar_card', ['kind'], unique=False)
    op.create_table('grammar_construction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('pattern', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_point.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_grammar_construction_grammar_point_id'), 'grammar_construction', ['grammar_point_id'], unique=False)
    op.create_table('grammar_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grammar_point_id', sa.Integer(), nullable=False),
    sa.Column('construction_key', sa.String(length=64), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_point.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_grammar_occ_point_src', 'grammar_occurrence', ['grammar_point_id', 'source_kind', 'source_id'], unique=False)
    op.create_index(op.f('ix_grammar_occurrence_grammar_point_id'), 'grammar_occurrence', ['grammar_point_id'], unique=False)
    op.create_table('misconception',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('errant_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('remedial_point_id', sa.Integer(), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['remedial_point_id'], ['grammar_point.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exercise_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('widget', sa.String(length=32), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('misconception_id', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['grammar_card.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconception.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_attempt_created_at'), 'exercise_attempt', ['created_at'], unique=False)
    op.create_table('grammar_card_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('fsrs_card', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['grammar_card.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    op.create_index(op.f('ix_grammar_card_state_due_at'), 'grammar_card_state', ['due_at'], unique=False)
    op.create_table('writing_attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original', sa.Text(), nullable=False),
    sa.Column('corrected', sa.Text(), nullable=True),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['grammar_card.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_attempt_created_at'), 'writing_attempt', ['created_at'], unique=False)
    op.create_table('writing_edit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('errant_type', sa.String(length=32), nullable=False),
    sa.Column('o_start', sa.Integer(), nullable=False),
    sa.Column('o_end', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('o_str', sa.Text(), nullable=False),
    sa.Column('c_str', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('misconception_id', sa.Integer(), nullable=True),
    sa.Column('grammar_point_id', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['writing_attempt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_point.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['misconception_id'], ['misconception.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_writing_edit_attempt_id'), 'writing_edit', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_writing_edit_errant_type'), 'writing_edit', ['errant_type'], unique=False)
    op.create_table('pronunciation_assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('completeness', sa.Float(), nullable=True),
    sa.Column('fluency', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('breaks', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('phonemes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recording_id'], ['shadow_recording.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pronunciation_assessment')
    op.drop_index(op.f('ix_writing_edit_errant_type'), table_name='writing_edit')
    op.drop_index(op.f('ix_writing_edit_attempt_id'), table_name='writing_edit')
    op.drop_table('writing_edit')
    op.drop_index(op.f('ix_writing_attempt_created_at'), table_name='writing_attempt')
    op.drop_table('writing_attempt')
    op.drop_index(op.f('ix_grammar_card_state_due_at'), table_name='grammar_card_state')
    op.drop_table('grammar_card_state')
    op.drop_index(op.f('ix_exercise_attempt_created_at'), table_name='exercise_attempt')
    op.drop_table('exercise_attempt')
    op.drop_table('misconception')
    op.drop_index(op.f('ix_grammar_occurrence_grammar_point_id'), table_name='grammar_occurrence')
    op.drop_index('ix_grammar_occ_point_src', table_name='grammar_occurrence')
    op.drop_table('grammar_occurrence')
    op.drop_index(op.f('ix_grammar_construction_grammar_point_id'), table_name='grammar_construction')
    op.drop_table('grammar_construction')
    op.drop_index(op.f('ix_grammar_card_kind'), table_name='grammar_card')
    op.drop_index(op.f('ix_grammar_card_grammar_point_id'), table_name='grammar_card')
    op.drop_table('grammar_card')
    op.drop_index('ix_word_phoneme_source', table_name='word_phoneme')
    op.drop_table('word_phoneme')
    op.drop_table('phoneme_difficulty')
    op.drop_index(op.f('ix_phoneme_card_state_due_at'), table_name='phoneme_card_state')
    op.drop_table('phoneme_card_state')
    op.drop_index(op.f('ix_phoneme_attempt_created_at'), table_name='phoneme_attempt')
    op.drop_index(op.f('ix_phoneme_attempt_card_key'), table_name='phoneme_attempt')
    op.drop_table('phoneme_attempt')
    op.drop_table('phoneme')
    op.drop_index('ix_minimal_pair_group_freq', table_name='minimal_pair')
    op.drop_index(op.f('ix_minimal_pair_contrast_group'), table_name='minimal_pair')
    op.drop_table('minimal_pair')
    op.drop_index(op.f('ix_grammar_point_shorthand_code'), table_name='grammar_point')
    op.drop_index(op.f('ix_grammar_point_cefr_level'), table_name='grammar_point')
    op.drop_index(op.f('ix_grammar_point_category'), table_name='grammar_point')
    op.drop_index('ix_grammar_point_cat_order', table_name='grammar_point')
    op.drop_table('grammar_point')
    # ### end Alembic commands ###
