"""book 加内置馆藏元数据字段

Revision ID: 1f36947e6c0f
Revises: 1439366fc2ed
Create Date: 2026-08-19 07:50:53.858803
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '1f36947e6c0f'
down_revision: str | None = '1439366fc2ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('difficulty', sa.String(length=16), nullable=True))
    op.add_column('book', sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('book', sa.Column('blurb', sa.Text(), nullable=True))
    op.add_column('book', sa.Column('external_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_book_external_id'), 'book', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_external_id'), table_name='book')
    op.drop_column('book', 'external_id')
    op.drop_column('book', 'blurb')
    op.drop_column('book', 'tags')
    op.drop_column('book', 'difficulty')
    # ### end Alembic commands ###
