"""生图资产加编辑链血缘列

Revision ID: 346adae3d445
Revises: fb72a36aad49
Create Date: 2026-08-20 03:25:25.144273
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '346adae3d445'
down_revision: str | None = 'fb72a36aad49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_asset', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('image_asset', sa.Column('op', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_image_asset_parent_id'), 'image_asset', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'image_asset', 'image_asset', ['parent_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image_asset', type_='foreignkey')
    op.drop_index(op.f('ix_image_asset_parent_id'), table_name='image_asset')
    op.drop_column('image_asset', 'op')
    op.drop_column('image_asset', 'parent_id')
    # ### end Alembic commands ###
