"""场景短文关联单词本

Revision ID: 3ad70919f1ca
Revises: a00707a43e2a
Create Date: 2026-08-18 20:29:09.228716
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '3ad70919f1ca'
down_revision: str | None = 'a00707a43e2a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('deck_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_article_deck_id'), 'article', ['deck_id'], unique=False)
    op.create_foreign_key(None, 'article', 'wordlist', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_index(op.f('ix_article_deck_id'), table_name='article')
    op.drop_column('article', 'deck_id')
    # ### end Alembic commands ###
