"""新增书签表

Revision ID: 427a2a59622a
Revises: 1f36947e6c0f
Create Date: 2026-08-19 07:59:49.279780
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '427a2a59622a'
down_revision: str | None = '1f36947e6c0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=240), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'paragraph_id', name='uq_bookmark_para')
    )
    op.create_index(op.f('ix_bookmark_article_id'), 'bookmark', ['article_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookmark_article_id'), table_name='bookmark')
    op.drop_table('bookmark')
    # ### end Alembic commands ###
