"""发音评测记录分数来源

Revision ID: 4d666e40c9c3
Revises: f0b5a5835fb3
Create Date: 2026-08-19 18:30:47.869263
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '4d666e40c9c3'
down_revision: str | None = 'f0b5a5835fb3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pronunciation_assessment', sa.Column('source', sa.String(length=16), server_default='heuristic', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pronunciation_assessment', 'source')
    # ### end Alembic commands ###
