"""候选视频元数据与难度预估字段

Revision ID: 60240f99d508
Revises: 76423544f9b0
Create Date: 2026-08-18 04:01:01.211144
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '60240f99d508'
down_revision: str | None = '76423544f9b0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_feed_item', sa.Column('view_count', sa.Integer(), nullable=True))
    op.add_column('video_feed_item', sa.Column('has_captions', sa.Boolean(), nullable=True))
    op.add_column('video_feed_item', sa.Column('caption_kind', sa.String(length=8), nullable=True))
    op.add_column('video_feed_item', sa.Column('wpm', sa.Float(), nullable=True))
    op.add_column('video_feed_item', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('video_feed_item', sa.Column('probe_meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_feed_item', 'probe_meta')
    op.drop_column('video_feed_item', 'difficulty')
    op.drop_column('video_feed_item', 'wpm')
    op.drop_column('video_feed_item', 'caption_kind')
    op.drop_column('video_feed_item', 'has_captions')
    op.drop_column('video_feed_item', 'view_count')
    # ### end Alembic commands ###
