"""管线多域 run泛化与产物层

Revision ID: 60fab1509c6c
Revises: 8615b99afd4e
Create Date: 2026-08-18 14:59:37.782125
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '60fab1509c6c'
down_revision: str | None = '8615b99afd4e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_interrupt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(length=48), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resume_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_interrupt_run', 'pipeline_interrupt', ['run_id', 'status'], unique=False)
    op.create_table('step_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=24), nullable=False, server_default='video'),
    sa.Column('subject_id', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('step', sa.String(length=48), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('blob_key', sa.String(length=255), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=True),
    sa.Column('produced_by_run_id', sa.Integer(), nullable=True),
    sa.Column('code_version', sa.String(length=32), nullable=True),
    sa.Column('human_edited', sa.Boolean(), nullable=False),
    sa.Column('edit_patch', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['produced_by_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifact_subject', 'step_artifact', ['domain', 'subject_id', 'step', 'created_at'], unique=False)
    op.create_index('uq_artifact_current', 'step_artifact', ['domain', 'subject_id', 'step'], unique=True, postgresql_where=sa.text('is_current'))
    op.add_column('pipeline_run', sa.Column('domain', sa.String(length=24), nullable=False, server_default='video'))
    op.add_column('pipeline_run', sa.Column('subject_id', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('pipeline_run', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # 历史 run 全部是视频域，subject_id 回填为原 video_id，不丢历史（FR-193）
    op.execute("UPDATE pipeline_run SET domain='video', subject_id=video_id WHERE video_id IS NOT NULL")
    op.create_index('ix_pipeline_run_subject', 'pipeline_run', ['domain', 'subject_id', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pipeline_run_subject', table_name='pipeline_run')
    op.alter_column('pipeline_run', 'video_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pipeline_run', 'subject_id')
    op.drop_column('pipeline_run', 'domain')
    op.drop_index('uq_artifact_current', table_name='step_artifact', postgresql_where=sa.text('is_current'))
    op.drop_index('ix_artifact_subject', table_name='step_artifact')
    op.drop_table('step_artifact')
    op.drop_index('ix_interrupt_run', table_name='pipeline_interrupt')
    op.drop_table('pipeline_interrupt')
    # ### end Alembic commands ###
