"""video enrich, subtitle words and youtube source

Revision ID: 6dbf641e2b4f
Revises: b4bc28c1ec52
Create Date: 2026-08-17 15:17:46.471915
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6dbf641e2b4f'
down_revision: str | None = 'b4bc28c1ec52'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_cue', sa.Column('phrases', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('subtitle_cue', sa.Column('words', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('subtitle_track', sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('video', sa.Column('error_kind', sa.String(length=16), nullable=True))
    op.add_column('video', sa.Column('title_zh', sa.String(length=512), nullable=True))
    op.add_column('video', sa.Column('summary_zh', sa.Text(), nullable=True))
    op.add_column('video', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('difficulty_detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('video', sa.Column('accent', sa.String(length=32), nullable=True))
    op.add_column('video', sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('video', sa.Column('vocab_count', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('enrich_status', sa.String(length=16), nullable=True))
    op.add_column('video', sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'enriched_at')
    op.drop_column('video', 'enrich_status')
    op.drop_column('video', 'vocab_count')
    op.drop_column('video', 'topics')
    op.drop_column('video', 'accent')
    op.drop_column('video', 'difficulty_detail')
    op.drop_column('video', 'difficulty')
    op.drop_column('video', 'summary_zh')
    op.drop_column('video', 'title_zh')
    op.drop_column('video', 'error_kind')
    op.drop_column('subtitle_track', 'meta')
    op.drop_column('subtitle_cue', 'words')
    op.drop_column('subtitle_cue', 'phrases')
    # ### end Alembic commands ###
