"""语法概念专栏

Revision ID: 728550fd187c
Revises: 4d666e40c9c3
Create Date: 2026-08-19 19:48:31.047335
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '728550fd187c'
down_revision: str | None = '4d666e40c9c3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grammar_concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('source_path', sa.String(length=400), nullable=False),
    sa.Column('chapter', sa.String(length=64), nullable=False),
    sa.Column('doc_title', sa.String(length=200), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('heading_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('layer', sa.String(length=16), nullable=False),
    sa.Column('why_active', sa.Text(), nullable=True),
    sa.Column('construction_keys', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('grammar_point_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('authored_by', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_grammar_concept_ch_order', 'grammar_concept', ['chapter', 'order_index'], unique=False)
    op.create_index(op.f('ix_grammar_concept_chapter'), 'grammar_concept', ['chapter'], unique=False)
    op.create_index(op.f('ix_grammar_concept_content_hash'), 'grammar_concept', ['content_hash'], unique=False)
    op.create_index(op.f('ix_grammar_concept_layer'), 'grammar_concept', ['layer'], unique=False)
    op.create_index(op.f('ix_grammar_concept_source_path'), 'grammar_concept', ['source_path'], unique=False)
    op.create_index(op.f('ix_grammar_concept_status'), 'grammar_concept', ['status'], unique=False)
    op.create_table('grammar_concept_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('fsrs_card', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('marked_known_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['grammar_concept.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id')
    )
    op.create_index(op.f('ix_grammar_concept_state_due_at'), 'grammar_concept_state', ['due_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grammar_concept_state_due_at'), table_name='grammar_concept_state')
    op.drop_table('grammar_concept_state')
    op.drop_index(op.f('ix_grammar_concept_status'), table_name='grammar_concept')
    op.drop_index(op.f('ix_grammar_concept_source_path'), table_name='grammar_concept')
    op.drop_index(op.f('ix_grammar_concept_layer'), table_name='grammar_concept')
    op.drop_index(op.f('ix_grammar_concept_content_hash'), table_name='grammar_concept')
    op.drop_index(op.f('ix_grammar_concept_chapter'), table_name='grammar_concept')
    op.drop_index('ix_grammar_concept_ch_order', table_name='grammar_concept')
    op.drop_table('grammar_concept')
    # ### end Alembic commands ###
