"""单词本v2 封面与场景本字段

Revision ID: 8615b99afd4e
Revises: d20a684b4b31
Create Date: 2026-08-18 13:33:37.162073
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '8615b99afd4e'
down_revision: str | None = 'd20a684b4b31'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordlist', sa.Column('emoji', sa.String(length=16), nullable=True))
    op.add_column('wordlist', sa.Column('color_seed', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('wordlist', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('wordlist', sa.Column('category', sa.String(length=32), nullable=True))
    op.add_column('wordlist', sa.Column('cefr', sa.String(length=4), nullable=True))
    op.add_column('wordlist', sa.Column('source', sa.String(length=16), nullable=False, server_default='import'))
    op.add_column('wordlist', sa.Column('status', sa.String(length=16), nullable=False, server_default='ready'))
    op.add_column('wordlist', sa.Column('pinned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wordlist', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('wordlist', sa.Column('daily_new_limit', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('wordlist_item', sa.Column('group_key', sa.String(length=24), nullable=True))
    op.add_column('wordlist_item', sa.Column('example_en', sa.Text(), nullable=True))
    op.add_column('wordlist_item', sa.Column('example_zh', sa.Text(), nullable=True))
    op.add_column('wordlist_item', sa.Column('dict_miss', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordlist_item', 'dict_miss')
    op.drop_column('wordlist_item', 'example_zh')
    op.drop_column('wordlist_item', 'example_en')
    op.drop_column('wordlist_item', 'group_key')
    op.drop_column('wordlist', 'daily_new_limit')
    op.drop_column('wordlist', 'archived_at')
    op.drop_column('wordlist', 'pinned_at')
    op.drop_column('wordlist', 'status')
    op.drop_column('wordlist', 'source')
    op.drop_column('wordlist', 'cefr')
    op.drop_column('wordlist', 'category')
    op.drop_column('wordlist', 'description')
    op.drop_column('wordlist', 'color_seed')
    op.drop_column('wordlist', 'emoji')
    # ### end Alembic commands ###
