"""自定义画风表

Revision ID: 94f737662905
Revises: 346adae3d445
Create Date: 2026-08-20 04:39:47.941167
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '94f737662905'
down_revision: str | None = '346adae3d445'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_style',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=48), nullable=False),
    sa.Column('hint', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('render', sa.Text(), nullable=False),
    sa.Column('palette', sa.Text(), nullable=False),
    sa.Column('lighting', sa.Text(), nullable=False),
    sa.Column('texture', sa.Text(), nullable=False),
    sa.Column('extra_avoid', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_image_style_category'), 'image_style', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_image_style_category'), table_name='image_style')
    op.drop_table('image_style')
    # ### end Alembic commands ###
