"""progress annotations custom wordlists document import

Revision ID: 9dd0a644dbf3
Revises: d663477770bd
Create Date: 2026-08-17 10:58:52.574546
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '9dd0a644dbf3'
down_revision: str | None = 'd663477770bd'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wordlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wordlist_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wordlist_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['wordlist_id'], ['wordlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wordlist_id', 'word', name='uq_wordlist_item_word')
    )
    op.create_table('reading_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('last_paragraph_ordinal', sa.Integer(), nullable=False),
    sa.Column('read_paragraphs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id')
    )
    op.create_table('annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_article_id'), 'annotation', ['article_id'], unique=False)
    op.add_column('article', sa.Column('file_key', sa.String(length=512), nullable=True))
    op.add_column('vocab_occurrence', sa.Column('video_id', sa.Integer(), nullable=True))
    op.add_column('vocab_occurrence', sa.Column('cue_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vocab_occurrence', 'cue_id')
    op.drop_column('vocab_occurrence', 'video_id')
    op.drop_column('article', 'file_key')
    op.drop_index(op.f('ix_annotation_article_id'), table_name='annotation')
    op.drop_table('annotation')
    op.drop_table('reading_progress')
    op.drop_table('wordlist_item')
    op.drop_table('wordlist')
    # ### end Alembic commands ###
