"""人工修正字段级时间戳

Revision ID: a00707a43e2a
Revises: 60fab1509c6c
Create Date: 2026-08-18 18:14:29.541635
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'a00707a43e2a'
down_revision: str | None = '60fab1509c6c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_sentence', sa.Column('edited_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('wordlist_item', sa.Column('edited_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordlist_item', 'edited_fields')
    op.drop_column('subtitle_sentence', 'edited_fields')
    # ### end Alembic commands ###
