"""vocab tables

Revision ID: a6790f17bb69
Revises: cc26ee0737e9
Create Date: 2026-08-17 07:11:59.891523
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'a6790f17bb69'
down_revision: str | None = 'cc26ee0737e9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vocab_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('lemma', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word')
    )
    op.create_table('vocab_occurrence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('context_text', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocab_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocab_occurrence')
    op.drop_table('vocab_entry')
    # ### end Alembic commands ###
