"""修复会话history列

Revision ID: b4d57ed12afc
Revises: 31d5bcaab90b
Create Date: 2026-08-18 05:53:58.824853
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b4d57ed12afc'
down_revision: str | None = '31d5bcaab90b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repair_session', sa.Column('history', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repair_session', 'history')
    # ### end Alembic commands ###
