"""场景本角色音色

Revision ID: b5af0e296236
Revises: 3ad70919f1ca
Create Date: 2026-08-18 20:48:26.884107
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b5af0e296236'
down_revision: str | None = '3ad70919f1ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wordlist', sa.Column('role_voices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordlist', 'role_voices')
    # ### end Alembic commands ###
