"""管线运行记录与字幕问题清单

Revision ID: c646ad1af6f0
Revises: 60240f99d508
Create Date: 2026-08-18 04:56:39.737338
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c646ad1af6f0'
down_revision: str | None = '60240f99d508'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('from_step', sa.String(length=32), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=True),
    sa.Column('config_override', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('code_version', sa.String(length=32), nullable=True),
    sa.Column('parent_run_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_run_id'], ['pipeline_run.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pipeline_run_status', 'pipeline_run', ['status'], unique=False)
    op.create_index('ix_pipeline_run_video', 'pipeline_run', ['video_id', 'id'], unique=False)
    op.create_table('pipeline_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_kind', sa.String(length=16), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('code_version', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['pipeline_run.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', 'attempt', name='uq_pipeline_step_attempt')
    )
    op.create_index('ix_pipeline_step_run', 'pipeline_step', ['run_id', 'ordinal'], unique=False)
    op.create_table('subtitle_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sentence_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['subtitle_sentence.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subtitle_issue_video', 'subtitle_issue', ['video_id', 'state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtitle_issue_video', table_name='subtitle_issue')
    op.drop_table('subtitle_issue')
    op.drop_index('ix_pipeline_step_run', table_name='pipeline_step')
    op.drop_table('pipeline_step')
    op.drop_index('ix_pipeline_run_video', table_name='pipeline_run')
    op.drop_index('ix_pipeline_run_status', table_name='pipeline_run')
    op.drop_table('pipeline_run')
    # ### end Alembic commands ###
