"""book status and error

Revision ID: cc26ee0737e9
Revises: fbd1c3df1fb2
Create Date: 2026-08-17 06:59:45.162065
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'cc26ee0737e9'
down_revision: str | None = 'fbd1c3df1fb2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('status', sa.String(length=16), nullable=False))
    op.add_column('book', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book', 'error')
    op.drop_column('book', 'status')
    # ### end Alembic commands ###
