"""subtitle_issue 增加修复动作字段

Revision ID: d20a684b4b31
Revises: b96f3b324640
Create Date: 2026-08-18 12:02:43.139050
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'd20a684b4b31'
down_revision: str | None = 'b96f3b324640'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subtitle_issue', sa.Column('action', sa.String(length=24), nullable=True))
    op.add_column('subtitle_issue', sa.Column('anchor', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subtitle_issue', 'anchor')
    op.drop_column('subtitle_issue', 'action')
    # ### end Alembic commands ###
