"""article status and user scenario

Revision ID: d663477770bd
Revises: 0538bbc594b2
Create Date: 2026-08-17 10:10:48.649536
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'd663477770bd'
down_revision: str | None = '0538bbc594b2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_scenario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('data', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.add_column('article', sa.Column('status', sa.String(length=16), server_default='ready', nullable=False))
    op.add_column('article', sa.Column('error', sa.Text(), nullable=True))
    op.add_column('article', sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'fetched_at')
    op.drop_column('article', 'error')
    op.drop_column('article', 'status')
    op.drop_table('user_scenario')
    # ### end Alembic commands ###
