"""video and subtitle tables

Revision ID: e2ec79da6354
Revises: a6790f17bb69
Create Date: 2026-08-17 08:11:51.547108
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e2ec79da6354'
down_revision: str | None = 'a6790f17bb69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('channel', sa.String(length=256), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('file_key', sa.String(length=512), nullable=True),
    sa.Column('thumb_key', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitle_track',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('lang', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['video.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subtitle_cue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['subtitle_track.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'ordinal', name='uq_subtitle_cue_pos')
    )
    op.create_index('ix_subtitle_cue_hash', 'subtitle_cue', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subtitle_cue_hash', table_name='subtitle_cue')
    op.drop_table('subtitle_cue')
    op.drop_table('subtitle_track')
    op.drop_table('video')
    # ### end Alembic commands ###
