"""cefrj_level 放宽到 16 字符

Revision ID: f0b5a5835fb3
Revises: 1cc5a88fe610
Create Date: 2026-08-19 14:34:43.880650
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f0b5a5835fb3'
down_revision: str | None = '1cc5a88fe610'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grammar_point', 'cefrj_level',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('grammar_point', 'cefrj_level',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=True)
    # ### end Alembic commands ###
