"""生图资产库与生图任务表

Revision ID: fb72a36aad49
Revises: 728550fd187c
Create Date: 2026-08-20 00:14:49.117471
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'fb72a36aad49'
down_revision: str | None = '728550fd187c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('display_key', sa.String(length=512), nullable=True),
    sa.Column('thumb_key', sa.String(length=512), nullable=True),
    sa.Column('mime', sa.String(length=32), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('target_key', sa.String(length=48), nullable=False),
    sa.Column('style_key', sa.String(length=48), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('prompt_structure', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('brief', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('alias', sa.String(length=48), nullable=True),
    sa.Column('model_reported', sa.String(length=64), nullable=True),
    sa.Column('size_req', sa.String(length=24), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('n_index', sa.Integer(), nullable=False),
    sa.Column('usage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('subject_domain', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('run_id', sa.Integer(), nullable=True),
    sa.Column('step', sa.String(length=48), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('favorite', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_asset_created_at'), 'image_asset', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_asset_sha256'), 'image_asset', ['sha256'], unique=True)
    op.create_index(op.f('ix_image_asset_status'), 'image_asset', ['status'], unique=False)
    op.create_index('ix_image_asset_subject', 'image_asset', ['subject_domain', 'subject_id'], unique=False)
    op.create_index(op.f('ix_image_asset_subject_domain'), 'image_asset', ['subject_domain'], unique=False)
    op.create_index(op.f('ix_image_asset_target_key'), 'image_asset', ['target_key'], unique=False)
    op.create_table('image_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_key', sa.String(length=48), nullable=False),
    sa.Column('idea', sa.Text(), nullable=True),
    sa.Column('subject_domain', sa.String(length=32), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('style_key', sa.String(length=48), nullable=True),
    sa.Column('size', sa.String(length=24), nullable=True),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('n', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=48), nullable=False),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('applied_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['applied_asset_id'], ['image_asset.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_job_created_at'), 'image_job', ['created_at'], unique=False)
    op.create_index(op.f('ix_image_job_status'), 'image_job', ['status'], unique=False)
    op.create_index(op.f('ix_image_job_target_key'), 'image_job', ['target_key'], unique=False)
    op.add_column('wordlist', sa.Column('cover_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wordlist', 'cover_key')
    op.drop_index(op.f('ix_image_job_target_key'), table_name='image_job')
    op.drop_index(op.f('ix_image_job_status'), table_name='image_job')
    op.drop_index(op.f('ix_image_job_created_at'), table_name='image_job')
    op.drop_table('image_job')
    op.drop_index(op.f('ix_image_asset_target_key'), table_name='image_asset')
    op.drop_index(op.f('ix_image_asset_subject_domain'), table_name='image_asset')
    op.drop_index('ix_image_asset_subject', table_name='image_asset')
    op.drop_index(op.f('ix_image_asset_status'), table_name='image_asset')
    op.drop_index(op.f('ix_image_asset_sha256'), table_name='image_asset')
    op.drop_index(op.f('ix_image_asset_created_at'), table_name='image_asset')
    op.drop_table('image_asset')
    # ### end Alembic commands ###
