"""initial core tables

Revision ID: fbd1c3df1fb2
Revises: 
Create Date: 2026-08-17 06:46:54.224368
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'fbd1c3df1fb2'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('context_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('lang_pair', sa.String(length=16), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_micros', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'content_hash', 'context_hash', 'kind', 'provider', 'lang_pair', 'version', name='uq_analysis_addr')
    )
    op.create_index('ix_analysis_lookup', 'analysis_result', ['scope', 'content_hash', 'context_hash', 'kind', 'provider', 'lang_pair'], unique=False, postgresql_where=sa.text('is_active'))
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('cover_key', sa.String(length=512), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('file_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dict_entry',
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('phonetic', sa.String(length=128), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('translation', sa.Text(), nullable=True),
    sa.Column('pos', sa.String(length=64), nullable=True),
    sa.Column('collins', sa.Integer(), nullable=True),
    sa.Column('oxford', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(length=128), nullable=True),
    sa.Column('bnc', sa.Integer(), nullable=True),
    sa.Column('frq', sa.Integer(), nullable=True),
    sa.Column('exchange', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('word')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_kind', sa.String(length=16), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('is_section', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_article_book', 'article', ['book_id', 'ordinal'], unique=False)
    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('tokens', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'ordinal', name='uq_paragraph_pos')
    )
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paragraph_id', sa.Integer(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=False),
    sa.Column('char_end', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['paragraph_id'], ['paragraph.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('paragraph_id', 'ordinal', name='uq_sentence_pos')
    )
    op.create_index('ix_sentence_hash', 'sentence', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sentence_hash', table_name='sentence')
    op.drop_table('sentence')
    op.drop_table('paragraph')
    op.drop_index('ix_article_book', table_name='article')
    op.drop_table('article')
    op.drop_table('dict_entry')
    op.drop_table('book')
    op.drop_index('ix_analysis_lookup', table_name='analysis_result', postgresql_where=sa.text('is_active'))
    op.drop_table('analysis_result')
    # ### end Alembic commands ###
